### ISSUE TITLE
There are two extensions from this repository "Change Case (Updated)" available in the Marketplace

### ISSUE THREAD

**Issue by vfonic** [hjdarnel/vscode-change-case#3]
I noticed there are two extensions v1.0.2 and v1.0.4 in the Marketplace. One should probably be removed.

<img width="286" alt="Screen Shot 2021-09-22 at 10 05 41" src="https://user-images.githubusercontent.com/67437/134306090-cce8e288-9966-4764-8c12-7a87cd16dee0.png">

**Comment by om-ha** [comment]
Seconded.

**Comment by hjdarnel** [comment]
Thanks for pointing this out @vfonic, I think it was an artifact of publishing manually before I had `semantic-release` setup. You can see now that the older version in the marketplace 404s.

https://marketplace.visualstudio.com/items?itemName=hjdarnel.change-case
