### ISSUE TITLE
feat: spongecase

### ISSUE THREAD

**Issue by druesendieb** [hjdarnel/vscode-change-case#4]
Hi @hjdarnel,
thanks for keeping this extension up to date!

I have a very low prio feature request:
Could you please bring the `sponge-case` package to the vscode extension: https://github.com/blakeembrey/change-case/tree/master/packages/sponge-case

Thanks in advance!

**Comment by hjdarnel** [comment]
I love it. I didn't know there was a sponge-case package. Thanks for the idea 😁 

@all-contributors please add @druesendieb for ideas!

Cheers
